### ISSUE TITLE
NYX

### ISSUE THREAD

**Issue by Mummy83** [OwenRay/minemon-report#13]
Op southExchange is de minmum deposit 1.0 NYX, alles lager dan dat is LOST. Ik heb de wallets er ff uitgehaald want weet niet of dat wel goed gaat. Ik zie namelijk dat de meeste transacties lager als 1 NYX zijn.

**Comment by OwenRay** [comment]
Via lokale wallet?

**Comment by Mummy83** [comment]
Mja kan, kijk wel even als ie weer hoog staat.

**Comment by OwenRay** [comment]
NYX is nu beschikbaar op stocks... dus dit is dan geen probleem meer;)

**Comment by Mummy83** [comment]
Oh beter, ga ik die ff aanpassen
