### ISSUE TITLE
Altminer

### ISSUE THREAD

**Issue by Mummy83** [OwenRay/minemon-report#16]
Die lijkt eruit te liggen. 

https://altminer.net/?address=F5ufYjUAXW5PbDV6FARgGEhyV8ekvZgaZe

**Comment by OwenRay** [comment]
ok, die zijn er vandoor gegaan....
kheb de pools verwijderd en gedeeltelijk nieuwe toegevoegd

**Comment by Mummy83** [comment]
Ok chill!
