### ISSUE TITLE
Wattage

### ISSUE THREAD

**Issue by Mummy83** [OwenRay/minemon-report#19]
Klopt het dat RIG 2 op IQ nognop vol vermogen draait?

**Comment by OwenRay** [comment]
ik wilde eerst op een rig checken of dat stabiel ging werken, nu heb ik de config ook doorgezet naar de tweede

**Comment by Mummy83** [comment]
ah zo, draait dus wel goed blijkbaar. Thuis draait ie ook nog lekker stil en koel in ECO mode :)
