### ISSUE TITLE
TUN Coins

### ISSUE THREAD

**Issue by Mummy83** [OwenRay/minemon-report#20]
Klopt die TUN coin wel? of zit er weer een fork aan te komen? tis vrij hoog lijkt me.

**Comment by OwenRay** [comment]
het is een beetje een twijfel geval... maar er zijn dus op t moment 3 chains, en men weet niet zeker op welke chain de exchanges zitten.... ik heb m voor de zekerheid maar uitgezet. iets te grote gok
