### ISSUE TITLE
Settings eerst naar swapfile wegschrijven

### ISSUE THREAD

**Issue by Mummy83** [OwenRay/minemon-report#22]
Hey Owen!

Fijne pasen :D, mn RIG is offline/gestopt met minen. Na reboot wil ie ook niet meer gaan minen. Lijkt hetzelfde als laatst. Kan hem wel pingen enzo.

Kijk maar of je tijd/zin hebt vandaag om ff te kijken.

Emmo

**Comment by OwenRay** [comment]
Hey Emmo, vervelend dat t weer gebeurd is:/ 
bij deze heb ik een oude config weer terug gezet, maar helaas zitten de nieuwe wallets daar niet in:(
geef het ff aan zodra je die erin hebt staan dan maak ik een backup van de settings voor het geval het weer gebeurd. Ik verander de titel van deze issue even en ga eraan werken dat deze issue zich niet meer voor zal doen.

**Comment by Mummy83** [comment]
Oh ja. Ik fiets di er vanavond wel even in. Thx weer.

**Comment by Mummy83** [comment]
Heb nu zo'n beetje alles er wel weer in zitten, dus mocht je tijd hebben graag ff backuppen.

Ik hoop dat de weergave van de 24h opbrengst onjuist is nu door de oude config-file?

**Comment by OwenRay** [comment]
Backup gemaakt en 24h opbrengst ook weer terug gezet

**Comment by Mummy83** [comment]
Leek te hangen op scriv coin vanochtend. Reboot gedaan maar komt nu niet online.

**Comment by OwenRay** [comment]
Ik zie m ook niet, dus kan je niet helpen, misschien nog een keer rebooten? Trouwens volgende keer beter de Coin aan de Blacklist toevoegen ipv rebooten.

**Comment by Mummy83** [comment]
Ok, ben nu niet thuis. Had trouwens de coin aan de blacklist toegevoegd vanochtend maar dat werkte niet.

**Comment by OwenRay** [comment]
wat heb je precies gedaan? wat gebeurde er precies? en wat verwachte je dat
er zou gebeuren?

**Comment by Mummy83** [comment]
De RIG was nog wel online, en was SCRIV aan het minen. De kaarten waren alleen koud en hij trok maar 150watt vermogen. SCRIV was op dat moment ook lang niet de coin met hoogste 24h reward. 

Dus ik dacht ik kijk even of ie stopt met SCRIV minen als ik die aan de blacklist toevoeg. 

Maar daar reageerde hij verder niet op. Dus heb ik hen met de power knop uitgezet en weer aan. Toen kwam ie niet online, dus jog een reboot gedaan en toen was ie er weer.

**Comment by OwenRay** [comment]
dan stond de machine denk ik helemaal offline of niet? weet je toevallig
nog wat de "last seen" was?

**Comment by Mummy83** [comment]
Last seen was paar seconden. Dus wel online. Maar gaf ook rare melding op de plek waar normaal de namen van de kaarten staan.

**Comment by OwenRay** [comment]
dan crashte hij waarschijnlijk herhaaldelijk op die coin, ik zal er wat
voor schrijven dat hij het crashen van de miner wat beter afvangt. zodat
hij nogsteeds nieuwe settings kan ontvangen.

**Comment by OwenRay** [comment]
Settings worden nu eerst naar een swapfile geschreven
