### ISSUE TITLE
Projected 24h income

### ISSUE THREAD

**Issue by Mummy83** [OwenRay/minemon-report#6]
Ha Owen,

Kan je tzt nog ff kijken naar die 'Projected 24h income' van de BOEMRIG? Die stond nog op 5GPU's oid dacht je.

thx,
Emmo

**Comment by OwenRay** [comment]
komt goed, ik heb daar morgenavond wel even tijd voor.
het heeft overigens geen invloed op de daadwerkelijke inkomsten, alléén de inschatting;)

**Comment by OwenRay** [comment]
is gefixt
