### ISSUE TITLE
Coins verversen loopt soms vast

### ISSUE THREAD

**Issue by Mummy83** [OwenRay/minemon-report#7]
Hey Owen,

De BOEMRIG heeft afgelopen nacht enkel QBIC lopen minen. 

De IQ RIG ook andere coins, daar is de waarde van de QBIC ook heel laag. 

Klopt het wel?

**Comment by OwenRay** [comment]
het lijkt erop dat het mechanlsme die tussen coins switched af en toe vastloopt, ga er naar kijken waarom dit gebeurd, voor nu is t opgelost met een restart van de app

**Comment by OwenRay** [comment]
denk ik nu gefixt, ff aanzien
